### ISSUE TITLE
有没有节点等待回调的demo？

### ISSUE THREAD

**Issue by Alvin1128** [jd-opensource/jd-easyflow#14]

**Comment by liyuliang-zz** [comment]
有的，可以基于回调事件触发流程流转，可参考下面两个例子：
https://github.com/jd-opensource/jd-easyflow/blob/master/easyflow-flow-extension/src/test/java/com/jd/easyflow/flow/ext/cases/session/SessionFlowTest.java
https://github.com/jd-opensource/jd-easyflow/blob/master/easyflow-flow/src/test/java/com/jd/easyflow/flow/cases/event/EventFlowTest.java

**Comment by Alvin1128** [comment]
感谢老板，这个如果不做数据持久化的话 能实现吗？

**Comment by Alvin1128** [comment]
还有另外一个问题咨询下，有没有工具可以把 flow_event_001.json 和 flow_session_001.json 反向解析成 bpmn 数据呢~

**Comment by liyuliang-zz** [comment]
> 感谢老板，这个如果不做数据持久化的话 能实现吗？

目前开源的部分便是核心引擎部分，纯内存计算，无持久化；目前需要持久化功能的话可基于监听器和过滤器做扩展实现。

**Comment by liyuliang-zz** [comment]
> 还有另外一个问题咨询下，有没有工具可以把 flow_event_001.json 和 flow_session_001.json 反向解析成 bpmn 数据呢~

目前没有的，json到bpmn需手工绘制。
