### ISSUE TITLE
关于BPMN，没有具体的文档吗？前端配置页面怎么打开？

### ISSUE THREAD

**Issue by nanhuaijin** [jd-opensource/jd-easyflow#15]

**Comment by liyuliang-zz** [comment]
下载代码后，直接双击https://github.com/jd-opensource/jd-easyflow/blob/master/easyflow-flow-bpmn/BPMNDesigner.html 文件便可打开，也可将相关文件集成到自己的工程中使用。
如果对前端页面有自定义要求，可基于本组件的BPMN规范使用bpmn前端组件(如bpmnjs)自定义实现。

**Comment by nanhuaijin** [comment]
还有，没太理解监听器和事件的用法。正常的审批应该是A审批通过，跳转到B审批（B监听A的结果），在Demo里面顺序执行下去的，在B节点判断中断，整个流程就结束了。实际想要的A审批通过停在B节点，等待B节点触发。B节点触发是重新调用一遍流程？？判断A通过直接走B？如果是这样不是太繁琐了？还是说监听器一直在监听B节点的数据库中审批状态，自动触发下一个节点？按照我的理解A审批调用A节点，A节点审批成功通知B节点用户审核，用户界面展示B节点，审核动作触发B节点的执行，这不就相当于分开定义节点，分开执行？事件和监听器应该怎么用呢？

**Comment by liyuliang-zz** [comment]
流程引擎支持从中间节点执行，只需要FlowParam中的开始节点设置为中间节点便可。
流程引擎也支持基于事件模式执行，有的事件流程中止，有的事件向后流程。
基于以上两个功能可实现您说的场景，不过目前流程持久化部分未开源，需自己基于流程的监听器或过滤器实现持久化的能力。
事件模型说明文档可见： https://gitee.com/JD-opensource/jd-easyflow/wikis/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E6%B5%81%E7%A8%8B%E5%BC%95%E6%93%8E%E4%BA%8B%E4%BB%B6%E6%A8%A1%E5%9E%8B%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
