### ISSUE TITLE
如何触发对外部系统的调用？

### ISSUE THREAD

**Issue by lonelystone545** [jd-opensource/jd-easyflow#7]
您好有几个小问题想咨询一下：
1. 目前这个框架在京东科技哪些业务线使用？
2. 开源的版本和内部版本完全一致么？
3. 有没有更详细的使用文档额？
4. 如果要对外部系统调用如何处理，后续还会有别的扩展么

**Comment by liyuliang-zz** [comment]
1. 目前这个框架在京东科技哪些业务线使用？金融业务线使用较多。
2. 开源的版本和内部版本完全一致么？完全一致，只是内部还有一些流程实例管理、任务审批等扩展模块暂未开源。
3. 有没有更详细的使用文档额？主要文档可参考https://github.com/jd-opensource/jd-easyflow/wiki 的相关页面，建议通过文档+源码+测试用例结合了解。
4. 如果要对外部系统调用如何处理，后续还会有别的扩展么。节点动作可以自定义，可自定义封装实现FlowNodeAction或通过spel调用普通java方法，通过FlowUtil也可读取到流程定义中的自定义配置信息；使用方可结合场景通过自定义节点动作、添加监听器、过滤器等实现自定义扩展，后续可能会有其他扩展模块的开源
