### ISSUE TITLE
建表脚本从哪来获取,项目中想使用此工作流

### ISSUE THREAD

**Issue by acaosj** [jd-opensource/jd-easyflow#9]
建表脚本从哪来获取,项目中想使用此工作流

**Comment by liyuliang-zz** [comment]
建表语句在: https://github.com/jd-opensource/jd-easyflow/blob/master/easyflow-flow-extension/src/main/script/process-latest.sql 中，但目前仅开源了建表语句，持久化和状态管理相关功能暂未开源，需自己通过流程引擎的listener或filter监听流程和节点状态流转来实现
